sonar.organization=alexanderpeter
sonar.projectKey=AlexanderPeter_cicd
sonar.projectName=CI/CD Project

sonar.sourceEncoding=UTF-8
sonar.sources=backend
sonar.exclusions=backend/.venv/**
sonar.tests=backend/tests
sonar.test.inclusions=**/tests/**/*.py
sonar.coverage.exclusions=backend/generated/**

sonar.python.version=3.11
sonar.python.projectBaseDir=backend
sonar.python.coverage.reportPaths=coverage.xml
