DROP TABLE IF EXISTS poll;
DROP TABLE IF EXISTS slot;

CREATE TABLE poll (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE slot (
    id SERIAL PRIMARY KEY,
    poll_id INTEGER NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_poll FOREIGN KEY (poll_id)
        REFERENCES poll (id)
        ON DELETE CASCADE
);
