
name: Trigger backend build

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  job_build_backend:
    uses: ./.github/workflows/backend_job.yml
