
name: Build backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  job_build_python:
    name: Build python code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Black check
        run: |
          source .venv/bin/activate
          black --check .

      - name: Run Pylint check
        run: |
          source .venv/bin/activate
          pylint . --fail-under=8.0

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: backend/htmlcov/
